detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gTheta <- c(0, 1, 3, 1, 0.5)
hTheta <- c(0.5, 3, 1, 1, 0)
sampleInput <- rghyp(100, Theta = gTheta)
qqghyp(sampleInput, Theta = gTheta)
dev.new()
ppghyp(sampleInput, Theta = gTheta)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
dev.new()
qqghyp(sampleInput, Theta = hTheta)
dev.new()
ppghyp(sampleInput, Theta = hTheta)
detach("package:HyperbolicDist")
