detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gTheta <- c(1, 2, 1.5, 1)
hTheta <- hyperbChangePars(2, 1, gTheta, noNames = TRUE)
hTheta <- c(hTheta[3], hTheta[4], hTheta[2], hTheta[1])
gmResult <- hyperbMean(Theta = gTheta)
gvResult <- hyperbVar(Theta = gTheta)
gsResult <- hyperbSkew(Theta = gTheta)
gkResult <- hyperbKurt(Theta = gTheta)
gmoResult <- hyperbMode(Theta = gTheta)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
hmResult <- hyperbMean(Theta = hTheta)
hvResult <- hyperbVar(Theta = hTheta)
hsResult <- hyperbSkew(Theta = hTheta)
hkResult <- hyperbKurt(Theta = hTheta)
hmoResult <- hyperbMode(Theta = hTheta)
detach("package:HyperbolicDist")

checkEqual(gmResult, hmResult, "hyperbMean")
checkEqual(gvResult, hvResult, "hyperbVar")
checkEqual(gsResult, hmResult, "hyperbSkew")
checkEqual(gkResult, hkResult, "hyperbKurt")
checkEqual(gmoResult, hmoResult, "hyperbMode")
