detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gParam <- c(0, 1, 3, 1, 0.5)
hParam <- c(0.5, 3, 1, 1, 0)
gmResult <- ghypMean(param = gParam)
gvResult <- ghypVar(param = gParam)
gsResult <- ghypSkew(param = gParam)
gkResult <- ghypKurt(param = gParam)
gmoResult <- ghypMode(param = gParam)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
hmResult <- ghypMean(param = hParam)
hvResult <- ghypVar(param = hParam)
hsResult <- ghypSkew(param = hParam)
hkResult <- ghypKurt(param = hParam)
hmoResult <- ghypMode(param = hParam)
detach("package:HyperbolicDist")

checkEqual(gmResult, hmResult, "ghypMean")
checkEqual(gvResult, hvResult, "ghypVar")
checkEqual(gsResult, hsResult, "ghypSkew")
checkEqual(gkResult, hkResult, "ghypKurt")
checkEqual(gmoResult, hmoResult, "ghypMode")
