detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gTheta <- c(2, 1, 1)
hTheta <- c(1, 2, 1)
sampleInput <- rgig(100, Theta = gTheta)
qqgig(sampleInput, Theta = gTheta)
dev.new()
ppgig(sampleInput, Theta = gTheta)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
dev.new()
qqgig(sampleInput, Theta = hTheta)
dev.new()
ppgig(sampleInput, Theta = hTheta)
detach("package:HyperbolicDist")
