detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gTheta <- c(2, 1, 1)
hTheta <- c(1, 2, 1)
gResult <- gigCalcRange(Theta = gTheta)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
hResult <- gigCalcRange(Theta = hTheta)
detach("package:HyperbolicDist")

checkEqual(gResult, hResult, "gigCalcRange")
