detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gTheta <- c(2, 1, 1)
hTheta <- c(1, 2, 1)
gmResult <- gigMean(Theta = gTheta)
gvResult <- gigVar(Theta = gTheta)
gsResult <- gigSkew(Theta = gTheta)
gkResult <- gigKurt(Theta = gTheta)
gmoResult <- gigMode(Theta = gTheta)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
hmResult <- gigMean(Theta = hTheta)
hvResult <- gigVar(Theta = hTheta)
hsResult <- gigSkew(Theta = hTheta)
hkResult <- gigKurt(Theta = hTheta)
hmoResult <- gigMode(Theta = hTheta)
detach("package:HyperbolicDist")

checkEqual(gmResult, hmResult, "gigMean")
checkEqual(gvResult, hvResult, "gigVar")
checkEqual(gsResult, hsResult, "gigSkew")
checkEqual(gkResult, hkResult, "gigKurt")
checkEqual(gmoResult, hmoResult, "gigMode")
