detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gTheta <- c(1, 2, 1.5, 1)
hTheta <- hyperbChangePars(2, 1, gTheta, noNames = TRUE)
hTheta <- c(hTheta[3], hTheta[4], hTheta[2], hTheta[1])
sampleInput <- rhyperb(100, Theta = gTheta)
gdResult <- dhyperb(sampleInput, Theta = gTheta)
gpResult <- phyperb(seq(-2, 5, 0.2), Theta = gTheta)
gqResult <- qhyperb(seq(0.1, 0.9, 0.1), Theta = gTheta)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
hdResult <- dhyperb(sampleInput, Theta = hTheta)
hpResult <- phyperb(seq(-2, 5, 0.2), Theta = hTheta)
hqResult <- qhyperb(seq(0.1, 0.9, 0.1), Theta = hTheta)
detach("package:HyperbolicDist")

checkEqual(gdResult, hdResult, "dhyperb")
checkEqual(gpResult, hpResult, "phyperb")
checkEqual(gqResult, hqResult, "qhyperb")
