detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gTheta <- c(3, 1, 1)
hTheta <- c(1, 1, 3)
sampleInput <- rskewlap(100, Theta = gTheta)
qqskewlap(sampleInput, Theta = gTheta)
dev.new()
ppskewlap(sampleInput, Theta = gTheta)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
dev.new()
qqskewlap(sampleInput, Theta = hTheta)
dev.new()
ppskewlap(sampleInput, Theta = hTheta)
detach("package:HyperbolicDist")
