detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gTheta <- c(0, 1, 3, 1, 0.5)
hTheta <- c(0.5, 3, 1, 1, 0)
gmResult <- ghypMean(Theta = gTheta)
gvResult <- ghypVar(Theta = gTheta)
gsResult <- ghypSkew(Theta = gTheta)
gkResult <- ghypKurt(Theta = gTheta)
gmoResult <- ghypMode(Theta = gTheta)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
hmResult <- ghypMean(Theta = hTheta)
hvResult <- ghypVar(Theta = hTheta)
hsResult <- ghypSkew(Theta = hTheta)
hkResult <- ghypKurt(Theta = hTheta)
hmoResult <- ghypMode(Theta = hTheta)
detach("package:HyperbolicDist")

checkEqual(gmResult, hmResult, "ghypMean")
checkEqual(gvResult, hvResult, "ghypVar")
checkEqual(gsResult, hsResult, "ghypSkew")
checkEqual(gkResult, hkResult, "ghypKurt")
checkEqual(gmoResult, hmoResult, "ghypMode")
