detach("package:GeneralizedHyperbolic")
detach("package:HyperbolicDist")
library(GeneralizedHyperbolic)
gTheta <- c(0, 1, 3, 1, 0.5)
hTheta <- c(0.5, 3, 1, 1, 0)
g0Result <- ghypMom(1, Theta = gTheta)
g1Result <- ghypMom(2, Theta = gTheta)
g2Result <- ghypMom(10, Theta = gTheta)
detach("package:GeneralizedHyperbolic")
library(HyperbolicDist)
h0Result <- ghypMom(1, Theta = hTheta)
h1Result <- ghypMom(2, Theta = hTheta)
h2Result <- ghypMom(10, Theta = hTheta)
detach("package:HyperbolicDist")

gResult <- c(g0Result, g1Result, g2Result)
hResult <- c(h0Result, h1Result, h2Result)

checkEqual(gResult, hResult, "ghypMom")
